spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 176.15.17.192
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8201
  
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
 
#启用hystrix熔断     
feign:
  hystrix:
    enabled: true
    
#暴露hystrix.stream端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream